### ISSUE TITLE
I getting this errors in the build process 

### ISSUE THREAD

**Issue by romelgomez** [RxJSInAction/rxjs-in-action#19]
After downloading the git repo and run `npm install && npm install -g gulp && gulp`

```
'rxjs' is imported by app/js/utils/cookies.js, but could not be resolved – treating it as an external dependency
'rxjs' is imported by app/js/editors.js, but could not be resolved – treating it as an external dependency
'jquery' is imported by app/js/editors.js, but could not be resolved – treating it as an external dependency
'codemirror' is imported by app/js/editors.js, but could not be resolved – treating it as an external dependency
'jquery' is imported by app/js/runtime.js, but could not be resolved – treating it as an external dependency
```

The next error, it fixed after update the gulpfile 

The sourceMap option has been renamed to "sourcemap" (lowercase "m") in Rollup. The old form is now deprecated in rollup-stream. options.entry is deprecated, use options.input

```
  return rollup({
    input: './app/js/runtime.js',
    sourcemap: true,

```

**Comment by paulpdaniels** [comment]
Thanks for the bug report @romelgomez! I'll take a look and push a fix.

**Comment by khtan** [comment]
Any chance of this getting fixed. Thanks

**Comment by Sacquer** [comment]
> After downloading the git repo and run `npm install && npm install -g gulp && gulp`
> 
> ```
> 'rxjs' is imported by app/js/utils/cookies.js, but could not be resolved – treating it as an external dependency
> 'rxjs' is imported by app/js/editors.js, but could not be resolved – treating it as an external dependency
> 'jquery' is imported by app/js/editors.js, but could not be resolved – treating it as an external dependency
> 'codemirror' is imported by app/js/editors.js, but could not be resolved – treating it as an external dependency
> 'jquery' is imported by app/js/runtime.js, but could not be resolved – treating it as an external dependency
> ```
> The next error, it fixed after update the gulpfile
> 
> The sourceMap option has been renamed to "sourcemap" (lowercase "m") in Rollup. The old form is now deprecated in rollup-stream. options.entry is deprecated, use options.input
> 
> ```
>   return rollup({
>     input: './app/js/runtime.js',
>     sourcemap: true,
> ```

I ran `npm audit fix` and thereafter `gulp`, still get the `sourceMap` and deprecated warnings but I'm able to open up :8080 and see the content.

**Comment by abhishe3571** [comment]
After cloning this repo and npm install && npm install -g gulp && gulp
I get a reference error: primordials is not defined
    `
at fs.js:27:26
    at req_ (/home/abhishek/rxjs-in-action/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/abhishek/rxjs-in-action/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/abhishek/rxjs-in-action/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js: #848:19)
    at require (internal/modules/cjs/helpers.js:74:18)

when I again try to run it then show the same error. How can I fix it?

**Comment by romelgomez** [comment]
@abhishe3571 @paulpdaniels 

with this work around its works properly:

`yarn install && yarn global add gulp && gulp`

![Screenshot from 2020-08-28 18-44-57](https://user-images.githubusercontent.com/2358251/91622879-c89ab080-e95e-11ea-8563-5ed7baf18d51.png)

**Comment by tehciolo** [comment]
I tried the `yarn` workaround and I still got the `ReferenceError: primordials is not defined`.

What fixed it for me was to also switch from node 12 to node 10.
